import { useRef } from 'react'
import { EditorContent, useEditor } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import Placeholder from '@tiptap/extension-placeholder'
import { Bold, Italic, List, Upload, X } from 'lucide-react'
import { fileToAsset, id } from '../storage/localStore'
import { usePortfolio } from '../contexts/PortfolioContext'
import type { Asset } from '../types/portfolio'
export const Button = ({ children, className = '', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) => <button className={`btn ${className}`} {...props}>{children}</button>
export const Empty = ({ children }: { children: React.ReactNode }) => <div className="empty">{children}</div>
export function Confirm({ open, title, text, onConfirm, onClose }: { open: boolean; title: string; text: string; onConfirm: () => void; onClose: () => void }) { if (!open) return null; return <div className="modal-backdrop"><div className="modal"><h3>{title}</h3><p>{text}</p><div className="actions"><Button className="ghost" onClick={onClose}>Cancel</Button><Button className="danger" onClick={onConfirm}>Delete</Button></div></div></div> }
export function RichText({ value, onChange }: { value: string; onChange: (value: string) => void }) { const editor = useEditor({ extensions: [StarterKit, Placeholder.configure({ placeholder: 'Write something meaningful...' })], content: value, onUpdate: ({ editor }) => onChange(editor.getHTML()) }); return <div className="editor"><div className="editor-tools"><Button type="button" onClick={() => editor?.chain().focus().toggleBold().run()}><Bold size={15}/></Button><Button type="button" onClick={() => editor?.chain().focus().toggleItalic().run()}><Italic size={15}/></Button><Button type="button" onClick={() => editor?.chain().focus().toggleBulletList().run()}><List size={15}/></Button></div><EditorContent editor={editor}/></div> }
export function FileUpload({ label, accept = '*/*', onUploaded }: { label: string; accept?: string; onUploaded: (asset: Asset) => void }) { const input = useRef<HTMLInputElement>(null); const { setData, toast } = usePortfolio(); const upload = async (file?: File) => { if (!file) return; if (file.size > 3 * 1024 * 1024) { toast('Please use files smaller than 3 MB for LocalStorage'); return } const item = await fileToAsset(file); const asset: Asset = { ...item, id: id(), createdAt: new Date().toISOString() }; setData(d => ({ ...d, assets: [...d.assets, asset], activity: [`Uploaded ${file.name}`, ...d.activity].slice(0, 12) })); onUploaded(asset); toast(`${file.name} uploaded locally`) }; return <><input ref={input} hidden type="file" accept={accept} onChange={e => upload(e.target.files?.[0])}/><Button type="button" className="ghost" onClick={() => input.current?.click()}><Upload size={15}/>{label}</Button></> }
export function AssetPreview({ asset, onRemove }: { asset?: Asset; onRemove?: () => void }) { if (!asset) return null; return <div className="asset-preview">{asset.type.startsWith('image/') ? <img src={asset.data} alt={asset.name}/> : <span>{asset.name}</span>} {onRemove && <button onClick={onRemove}><X size={14}/></button>}</div> }
